export const IMGS = {
  hero1:      "/images/hero1.jpg",
  hero2:      "/images/hero2.jpg",
  hero3:      "/images/hero3.jpg",
  about:      "/images/about.jpg",
  counterBg:  "/images/counter_bg.jpg",
  ctaBg:      "/images/cta_bg.jpg",
  portfolio1: "/images/portfolio1.jpg",
  portfolio2: "/images/portfolio2.jpg",
  portfolio3: "/images/portfolio3.jpg",
  portfolio4: "/images/portfolio4.jpg",
  portfolio5: "/images/portfolio5.jpg",
  portfolio6: "/images/portfolio6.jpg",
  blog1:      "/images/blog1.jpg",
  blog2:      "/images/blog2.jpg",
  blog3:      "/images/blog3.jpg",
  team1:      "/images/team1.jpg",
  team2:      "/images/team2.jpg",
  team3:      "/images/team3.jpg",
  portfolio7:  "/images/portfolio7.jpg",
  portfolio8:  "/images/portfolio8.jpg",
  portfolio9:  "/images/portfolio9.jpg",
  portfolio10: "/images/portfolio10.jpg",
  portfolio11: "/images/portfolio11.jpg",
  portfolio12: "/images/portfolio12.jpg",
  aboutHero:   "/images/about_hero.jpg",
  teamCulture: "/images/team_culture.jpg",
};
